### ISSUE TITLE
Rename this to attr or attributes

### ISSUE THREAD

**Issue by jimdebeer** [vigour-io/brisky-props#4]
props mimics react

**Comment by jimdebeer** [comment]
guys can we decide upon this now?

**Comment by nfrade** [comment]
Attributes make sense. It's the mainly the dom element attributes.

**Comment by jimdebeer** [comment]
its only dom attributes ;)

**Comment by nfrade** [comment]
There you go

**Comment by nikoloza** [comment]
Yep

**Comment by jimdebeer** [comment]
okidoki will do this soon will warn you to pull all repos

**Comment by jimdebeer** [comment]
done its is now part of brisky-render
